"""empty message

Revision ID: 41fbce1e16cb
Revises: 62bc146eeddc
Create Date: 2022-08-15 14:50:28.333485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fbce1e16cb'
down_revision = '62bc146eeddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'users', ['poster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'poster_id')
    # ### end Alembic commands ###
