"""empty message

Revision ID: 62bc146eeddc
Revises: cefb5664f81b
Create Date: 2022-08-15 14:49:19.567209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bc146eeddc'
down_revision = 'cefb5664f81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('user_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
