"""empty message

Revision ID: 7d74252135be
Revises: bb4f1b544061
Create Date: 2022-08-15 18:58:34.552324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d74252135be'
down_revision = 'bb4f1b544061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'question', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('question', 'poster_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('poster_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    # ### end Alembic commands ###
