"""empty message

Revision ID: 91b3a79f65e1
Revises: e30bbf170545
Create Date: 2022-08-19 21:59:26.273881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b3a79f65e1'
down_revision = 'e30bbf170545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'question', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('question', 'poster_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('poster_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    # ### end Alembic commands ###
