"""empty message

Revision ID: a52613e9a26f
Revises: 5f48717a6c43
Create Date: 2022-08-30 21:24:46.657346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52613e9a26f'
down_revision = '5f48717a6c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_fullname', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_post_heading', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('heading', sa.VARCHAR(length=50), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_heading', 'post', ['heading'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('linkedin', sa.VARCHAR(length=50), nullable=False),
    sa.Column('github', sa.VARCHAR(length=45), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github'),
    sa.UniqueConstraint('linkedin')
    )
    op.create_index('ix_user_fullname', 'user', ['fullname'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
