"""empty message

Revision ID: bb4f1b544061
Revises: 41fbce1e16cb
Create Date: 2022-08-15 18:56:48.021691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4f1b544061'
down_revision = '41fbce1e16cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('question', 'poster_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('poster_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'user_id')
    # ### end Alembic commands ###
